{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message-broker-engine.fullname" . }}-secrets
  labels:
    {{- include "message-broker-engine.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  # Elasticsearch credentials for logging to Kibana
  {{- if .Values.secrets.elasticsearch.endpoint }}
  elasticsearch-endpoint: {{ .Values.secrets.elasticsearch.endpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearch.username }}
  elasticsearch-username: {{ .Values.secrets.elasticsearch.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.elasticsearch.password }}
  elasticsearch-password: {{ .Values.secrets.elasticsearch.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.tls_cert }}
  tls.crt: {{ .Values.secrets.tls_cert | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tls_key }}
  tls.key: {{ .Values.secrets.tls_key | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.config.security.enable_tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message-broker-engine.fullname" . }}-tls
  labels:
    {{- include "message-broker-engine.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls_cert | b64enc }}
  tls.key: {{ .Values.secrets.tls_key | b64enc }}
{{- end }}
