{{- if .Values.config.security.enable_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message-broker-engine.fullname" . }}-secret
  labels:
    {{- include "message-broker-engine.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  tls.crt: {{ .Values.secrets.tls_cert | b64enc }}
  tls.key: {{ .Values.secrets.tls_key | b64enc }}
{{- end }}

{{- if .Values.config.security.enable_tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message-broker-engine.fullname" . }}-tls
  labels:
    {{- include "message-broker-engine.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls_cert | b64enc }}
  tls.key: {{ .Values.secrets.tls_key | b64enc }}
{{- end }}
